[package]
name = "termcalc"
version = "0.1.0"
description = "Terminal calculator"
edition = "2021"

[lib]
name = "tc"
path = "src/lib/lib.rs"

[[bin]]
name = "tc"
path = "src/bin.rs"

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
colored = "2.1.0"
